### PR TITLE
A C++ Parser for TESLA Grammar.

### PR DESCRIPTION
**Pull request by spopa01**

### CODE REVIEW

**Comment by spopa01** [comment]
The parser is self-contained into Parser.h/.cpp, it doesn't require any change to the rest of the project, it's using Boost::Spirit and I think that it will help this project to move forward.

**Comment by spopa01** [comment]
The parser is self-contained (Parser.h/.cpp), it doesn't require any changes to the rest of the code base, it's using Boost::Spirit and I think that it can help this project to move forward.

**Comment by cugola** [comment]
I appreciate the contribution but a parser was already included into the 
project, as part of the java client. We feel that to be the right place 
to have a parser. I suggest to play with that parser and contribute to 
it if you feel your contribution to be more complete.

**Comment by spopa01** [comment]
I totally agree that the things should remain as you need them for your current research, but a C++ parser would greatly simplify the (automatic) testing of the library/engine; plus not everyone interested in evaluating the TRex Engine is also interested in using the current Java-Client -> C++-Server -> C++-Engine kind of architecture. I will close the pull request at the moment but feel free to use it later on if you change your mind.

**Pull request closed without merging**
